# Generated by Django 5.0.6 on 2024-11-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='diseases',
            field=models.JSONField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='symptoms',
            field=models.JSONField(default=123),
            preserve_default=False,
        ),
    ]
