# Generated by Django 5.0.6 on 2024-12-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_diseases_quiz_symptom_disease_pairs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='symptom_disease_pairs',
            new_name='diseases',
        ),
        migrations.AddField(
            model_name='quiz',
            name='symptoms',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
