# Generated by Django 5.0.6 on 2024-12-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_symptom_disease_pairs_quiz_diseases_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='diseases',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='symptoms',
        ),
    ]
